from collections import OrderedDict

# Define Output Columns
internalHeader = [
    "PID",
    "ChannelNo",
    "TXDate",
    "ActualTime",
    "FullTitleEng",
    "FullTitleChi",
    "SponsorTextStuntEng",
    "SponsorTextStuntChi",
    "BrandNameEng",
    "BrandNameChi",
    "EditionVersionEng",
    "EditionVersionChi",
    "SeasonNo",
    "SeasonNameEng",
    "SeasonNameChi",
    "EpisodeNo",
    "EpisodeNameEng",
    "EpisodeNameChi",
    "SynopsisEng",
    "SynopsisChi",
    "ShortSynopsisEng",
    "ShortSynopsisChi",
    "PremierOld",
    "Premier",
    "IsLive",
    "Classification",
    "Genre",
    "SubGenre",
    "DirectorProducerEng",
    "DirectorProducerChi",
    "CastEng",
    "CastChi",
    "OriginalLang",
    "Bilingual",
    "AudioLang",
    "SubtitleLang",
    "RegionCode",
    "FirstReleaseYear",
    "IsEpisodic",
    "IsVOD",
    "PortraitImage",
    "ImageWithTitle",
    "RecordableForCatchUp",
    "CPInternalUniqueID",
    "CPInternalSeriesID",
    "Recordable",
    "IsNPVRProg",
    "IsRestartTV",
    "EffectiveDate",
    "ExpirationDate",
    "OwnerChannel",
    "ProgrammeNameEng",
    "ProgrammeNameChi",
    "imdbID",
    "MediaID",
    "HKTAMChannelID",
    "HKTAMProgramID",
    "HKTAMEpisodeID",
]

preV1506HeaderMapping = OrderedDict([
    ("PID","PID"),
    ("ChannelNo","Channel #"),
    ("TXDate","TX Date"),
    ("ActualTime","Actual Time"),
    ("FullTitleEng","Full Title (English) 40 Characters"),
    ("FullTitleChi","Full Title (Chinese) Max 24 Characters"),
    ("SponsorTextStuntEng","Sponsor text / Stunt (English)"),
    ("SponsorTextStuntChi","Sponsor text / Stunt (Chinese)"),
    ("BrandNameEng","English Brand Name Max 360 Characters"),
    ("BrandNameChi","Chinese Brand Name Max 360 Characters"),
    ("EditionVersionEng","Edition / Version (English)"),
    ("EditionVersionChi","Edition / Version (Chinese)"),
    ("SeasonNo","Season no Max 3 digits"),
    ("SeasonNameEng","Season Name (English)"),
    ("SeasonNameChi","Season Name (Chinese)"),
    ("EpisodeNo","Episode no Max 5 digits"),
    ("EpisodeNameEng","Episode Name (English) (max 50 Chars)"),
    ("EpisodeNameChi","Episode Name (Chinese) (max 50 Chars)"),
    ("SynopsisEng","Programme Synopsis (English) Max 180 Characters"),
    ("SynopsisChi","Programme Synopsis (Chinese) Max 130 Characters"),
    ("ShortSynopsisEng","Short Programme Synopsis (English) (max. 120 Chars)"),
    ("ShortSynopsisChi","Short Programme Synopsis (Chinese) (max. 120 Chars)"),
    ("PremierOld","Premier"),
    ("Premier","Premiere (Y/N)"),
    ("IsLive","Is Live (Y/N)"),
    ("Classification","Classification"),
    ("Genre","Genre"),
    ("SubGenre","Sub-Genre"),
    ("DirectorProducerEng","Director (English) Max 100 Characters"),
    ("DirectorProducerChi","Director (Chinese) Max 100 Characters"),
    ("CastEng","Actor (English) Max 100 Characters"),
    ("CastChi","Actor (Chinese) Max 100 Characters"),
    ("OriginalLang","Original Language Max 40 Characters"),
    ("AudioLang","Audio language"),
    ("SubtitleLang","Subtitle language"),
    ("RegionCode","Region Code Max  2 Characters"),
    ("FirstReleaseYear","First release year Max 4 digits"),
    ("IsEpisodic","Episodic (Y/N)"),
    ("ImageWithTitle","Image with title  (Y/N)"),
    ("PortraitImage","Portrait Image"),
    ("CPInternalUniqueID","CP internal unique ID"),
    ("CPInternalSeriesID","CP Internal Series ID"),
    ("Recordable","Recordable"),
    ("IsNPVRProg","Is NPVR Prog"),
    ("IsRestartTV","Is Restart TV"),
    ("EffectiveDate","effective_date"),
    ("ExpirationDate","expiration_date"),
    ("HKTAMChannelID", "HKTAM Channel ID (max. 5 chars)"),
    ("HKTAMProgramID", "HKTAM Program ID (max. 5 chars)"),
    ("HKTAMEpisodeID", "HKTAM Episode ID (max. 6 chars)"),
])

postV1506HeaderMapping = OrderedDict([
    ("PID","PID"),
    ("ChannelNo","Channel #"),
    ("TXDate","TX Date"),
    ("ActualTime","Actual Time"),
    ("FullTitleEng","Full Title (English) Max 40 Characters"),
    ("FullTitleChi","Full Title (Chinese) Max 24 Characters"),
    ("SponsorTextStuntEng","Sponsor text / Stunt (English)"),
    ("SponsorTextStuntChi","Sponsor text / Stunt (Chinese)"),
    ("BrandNameEng","Brand name (English)"),
    ("BrandNameChi","Brand name (Chinese)"),
    ("EditionVersionEng","Edition / Version (English)"),
    ("EditionVersionChi","Edition / Version (Chinese)"),
    ("SeasonNo","Season no. (max 3 digits)"),
    ("SeasonNameEng","Season Name (English)"),
    ("SeasonNameChi","Season Name (Chinese)"),
    ("EpisodeNo","Episode no. (max 5 digits)"),
    ("EpisodeNameEng","Episode name (English)"),
    ("EpisodeNameChi","Episode name (Chinese)"),
    ("SynopsisEng","Synopsis (English)"),
    ("SynopsisChi","Synopsis (Chinese)"),
    ("ShortSynopsisEng","Short Synopsis (English) (max 120 chars)"),
    ("ShortSynopsisChi","Short Synopsis (Chinese) (max 120 chars)"),
#    ("PremierOld","Premier"),
    ("Premier","Premiere (Y/N)"),
    ("IsLive","Is Live (Y/N)"),
    ("Classification","Classification"),
    ("Genre","Genre"),
    ("SubGenre","Sub-Genre"),
    ("DirectorProducerEng","Director / Producer (English)"),
    ("DirectorProducerChi","Director / Producer (Chinese)"),
    ("CastEng","Cast (English)"),
    ("CastChi","Cast (Chinese)"),
    ("OriginalLang","Original language (max 50 chars)"),
    ("Bilingual", "Bilingual (Y/N)"),
    ("AudioLang","Audio language"),
    ("SubtitleLang","Subtitle language"),
    ("RegionCode","Region Code (max 2 chars)"),
    ("FirstReleaseYear","First release year (max 4 digits)"),
    ("IsEpisodic","Episodic (Y/N)"),
    ("IsVOD", "is VOD (Y/N)"),
    ("PortraitImage","Portrait Image"),
    ("ImageWithTitle","Image with title  (Y/N)"),
    ("RecordableForCatchUp","Recordable for Catch-up (Y/N)"),
    ("CPInternalUniqueID","CP Internal unique ID"),
    ("CPInternalSeriesID","CP Internal Series ID"),
    ("Recordable","Recordable"),
    ("IsNPVRProg","Is NPVR Prog"),
    ("IsRestartTV","Is Restart TV"),
    ("EffectiveDate","effective_date"),
    ("ExpirationDate","expiration_date"),
    ("MediaID", "Media ID (max. 12 chars)"),
    ("HKTAMChannelID", "HKTAM Channel ID (max. 5 chars)"),
    ("HKTAMProgramID", "HKTAM Program ID (max. 5 chars)"),
    ("HKTAMEpisodeID", "HKTAM Episode ID (max. 6 chars)"),
])

# Define Output Columns for non-linear
nlInternalHeader = [
    'StartDate',
    'EndDate',
    'Duration',
    'LibraryEng',
    'LibraryChi',
    'SponsorTextStuntEng',
    'SponsorTextStuntChi',
#    'FullTitleEngOld',
#    'FullTitleChiOld',
    'SeriesID',
    'BrandNameEng',
    'BrandNameChi',
    'EditionVersionEng',
    'EditionVersionChi',
    'SeasonNo',
    'SeasonNameEng',
    'SeasonNameChi',
    'EpisodeNo',
    'EpisodeNameEng',
    'EpisodeNameChi',
    'SynopsisEng',
    'SynopsisChi',
    'ShortSynopsisEng',
    'ShortSynopsisChi',
    'DirectorProducerEng', 
    'DirectorProducerChi',
    'CastEng', 
    'CastChi', 
#    'CastEngOld',
#    'CastChiOld', 
#    'DirectorEngOld',
#    'DirectorChiOld', 
    'Category', 
#    'CategoryChiOld',
    'Genre', 
    'SubGenre', 
#    'SubGenreChiOld',
    'OriginalLang', 
    'AudioLang',
    'SubtitleLang', 
#    'SubtitleChiOld',
#    'LanguageEngOld',
#    'LanguageChiOld', 
    'RegionCode',
    'FirstReleaseYear', 
    'EventDate', 
    'OpeningSlate',
    'AudioSlate', 
    'AdvisorySlate', 
    'TVClassification',
    'WebClassification', 
    'DisplayOrder', 
    'MPEG4HD18', 
    'MPEG4HD',
    'MPEG4SD', 
    'WebPlayReady', 
    'NoAppCheckout',
    '3DContent', 
    '51Audio', 
    'PosterTag', 
    'PortraitImage',
    'LandscapeImage', 
    'ImageWithTitle', 
    'ExternalID1',
    'ExternalID2', 
    'CPInternalUniqueID', 
    'CPInternalSeriesID',
    'Poster1', 
    'Poster2', 
    'Poster3', 
    'Poster4', 
    'HDPoster1',
    'HDPoster2', 
    'WebPoster1', 
    'WebPoster2',
    'Tag'
]

nlPostV1506HeaderMapping = OrderedDict([
    ('StartDate', 'Start Date (YYYYMMDD)'),
    ('EndDate', 'End Date (YYYYMMDD)'),
    ('Duration', 'Duration (HH:MM:SS)'),
    ('LibraryEng', 'Library (English)'),
    ('LibraryChi', 'Library (Chinese)'),
    ('SponsorTextStuntEng', 'Sponsor text / Stunt (English)'),
    ('SponsorTextStuntChi', 'Sponsor text / Stunt (Chinese)'),
#    ('FullTitleEngOld', 'Full Title (English) (max. 35 chars)'),
#    ('FullTitleChiOld', 'Full Title (Chinese) (max. 17 chars)'),
    ('SeriesID', 'Series ID'),
    ('BrandNameEng', 'Brand name (English)'),
    ('BrandNameChi', 'Brand name (Chinese)'),
    ('EditionVersionEng', 'Edition / Version (English)'),
    ('EditionVersionChi', 'Edition / Version (Chinese)'),
    ('SeasonNo', 'Season no. (max 3 digits)'),
    ('SeasonNameEng', 'Season Name (English)'),
    ('SeasonNameChi', 'Season Name (Chinese)'),
    ('EpisodeNo', 'Episode no. (max 5 digits)'),
    ('EpisodeNameEng', 'Episode name (English)'),
    ('EpisodeNameChi', 'Episode name (Chinese)'),
    ('SynopsisEng', 'Synopsis (English)'),
    ('SynopsisChi', 'Synopsis (Chinese)'),
    ('ShortSynopsisEng', 'Short Synopsis (English) (max. 120 Chars)'),
    ('ShortSynopsisChi', 'Short Synopsis (Chinese) (max. 120 Chars)'),
    ('DirectorProducerEng', 'Director / Producer (English)'),
    ('DirectorProducerChi', 'Director / Producer (Chinese)'),
    ('CastEng', 'Cast (English)'),
    ('CastChi', 'Cast (Chinese)'),
#    ('CastEngOld', 'Cast (English) (max. 22 chars)'),
#    ('CastChiOld', 'Cast (Chinese) (max. 17 chars)'),
#    ('DirectorEngOld', 'Director (English) (max. 22 chars)'),
#    ('DirectorChiOld', 'Director (Chinese) (max. 17 chars)'),
    ('Category', 'Category'),
#    ('CategoryChiOld', 'Category (Chinese)'),
    ('Genre', 'Genre'),
    ('SubGenre', 'Sub-Genre'),
#    ('SubGenreChiOld', 'Sub Genre (Chinese) (max. 100 chars)'),
    ('OriginalLang', 'Original language (max 50 chars)'),
    ('AudioLang', 'Audio language'),
    ('SubtitleLang', 'Subtitle language'),
#    ('SubtitleChiOld', 'Subtitle (Chinese) (max. 500 chars)'),
#    ('LanguageEngOld', 'Language (English) (max. 22 chars)'),
#    ('LanguageChiOld', 'Language (Chinese) (max. 17 chars)'),
    ('RegionCode', 'Region Code (max. 2 chars)'),
    ('FirstReleaseYear', 'First Release Year'),
    ('EventDate', 'Event date (YYYYMMDD)'),
    ('OpeningSlate', 'Opening slate'),
    ('AudioSlate', 'Audio slate'),
    ('AdvisorySlate', 'Advisory slate'),
    ('TVClassification', 'TV Classification'),
    ('WebClassification', 'Web Classification'),
    ('DisplayOrder', 'Display Order'),
    ('MPEG4HD18', 'MPEG4HD18'),
    ('MPEG4HD', 'MPEG4HD'),
    ('MPEG4SD', 'MPEG4SD'),
    ('WebPlayReady', 'Web (Play Ready) (Y/N)'),
    ('NoAppCheckout', 'No App Checkout (Y/N)'),
    ('3DContent', '3D Content (Y/N)'),
    ('51Audio', '5.1 Audio (Y/N)'),
    ('PosterTag', 'Poster Tag'),
    ('PortraitImage', 'Portrait Image'),
    ('LandscapeImage', 'Landscape Image'),
    ('ImageWithTitle', 'Image with title (Y/N)'),
    ('ExternalID1', 'External ID 1'),
    ('ExternalID2', 'External ID 2'),
    ('CPInternalUniqueID', 'CP Internal unique ID'),
    ('CPInternalSeriesID', 'CP Internal Series ID'),
    ('Poster1', 'Poster 1'),
    ('Poster2', 'Poster 2'),
    ('Poster3', 'Poster 3'),
    ('Poster4', 'Poster 4'),
    ('HDPoster1', 'HD Poster 1'),
    ('HDPoster2', 'HD Poster 2'),
    ('WebPoster1', '[Web] Poster 1'),
    ('WebPoster2', '[Web] Poster 2'),
    ('Tag', 'Tag (max. 500 chars)')
])

nlAltInternalHeaderMapping = OrderedDict([
    ('Short Synopsis (English) (max 120 chars)', 'ShortSynopsisEng'),
    ('Short Synopsis (Chinese) (max 120 Chars)', 'ShortSynopsisChi'),
    ('Short Synopsis (English) (max. 110 Chars)', 'ShortSynopsisEng'),
    ('Short Synopsis (Chinese) (max. 110 Chars)', 'ShortSynopsisChi'),
    ('Image with title  (Y/N)', 'ImageWithTitle'),
    ('Region Code (max 2 chars)', 'RegionCode'),
    ('First release year', 'FirstReleaseYear'),
    ('Opening Slate', 'OpeningSlate'),
    ('Audio Slate', 'AudioSlate'),
    ('Advisory Slate', 'AdvisorySlate'),
    ('Event Date (YYYYMMDD)', 'EventDate'),
    ('Event date', 'EventDate')  
])

nlAvailAltPostV1506HeaderMapping= OrderedDict([
    ('Channel No.', 'Channel No.'),
    ('Channel', 'Channel'),
    ('NPVR(Y/N)', 'NPVR (Y/N)'),
    ('NPVR (Y/N)', 'NPVR (Y/N)'),
    ('Recordable for Catch-up (Y/N)', 'NPVR (Y/N)'),
    ('Full Title (English) (max. 35 chars)', 'Full Title (English)'),
    ('Full Title (Chinese) (max. 17 chars)', 'Full Title (Chinese)'),
    ('Full Title (English)', 'Full Title (English)'),
    ('Full Title (Chinese)', 'Full Title (Chinese)')
])

nlExceptInputHeader = [
    'Cast (English) (max. 22 chars)',
    'Cast (Chinese) (max. 17 chars)',
    'Director (English) (max. 22 chars)',
    'Director (Chinese) (max. 17 chars)',
    'Category (Chinese)',
    'Sub Genre (Chinese) (max. 100 chars)',
    'Subtitle (Chinese) (max. 500 chars)',
    'Language (English) (max. 22 chars)',
    'Language (Chinese) (max. 17 chars)'    
]

pwhHeaderMapping = OrderedDict([
("PID", "progId"),
("ChannelNo", "channelId"), 
("TXDate", "txDate"), 
("ActualTime", "actualTime"), 
("FullTitleEng", "engName"), 
("FullTitleChi", "chiName"), 
("SponsorTextStuntEng", "engSponsor"), 
("SponsorTextStuntChi", "chiSponsor"),
("BrandNameEng", "engSeries"),
("BrandNameChi", "chiSeries"),
("EditionVersionEng", "engVersion"),
("EditionVersionChi", "chiVersion"),
("SeasonNo", "seasonNum"),
("SeasonNameEng", "engSeasonName"),
("SeasonNameChi", "chiSeasonName"),
("EpisodeNo", "episodeNum"),
("EpisodeNameEng", "engEpisodeName"),
("EpisodeNameChi", "chiEpisodeName"),
("SynopsisEng", "engSynopsis"),
("SynopsisChi", "chiSynopsis"),
("ShortSynopsisEng", "engShortSynopsis"), 
("ShortSynopsisChi", "chiShortSynopsis"),
("Premiere", "premiere"),
("IsLive", "isLive"), 
("Classification", "classification"),
("Genre", "genre"), 
("SubGenre", "subGenre"),
("DirectorProducerEng", "engDirector"),
("DirectorProducerChi", "chiDirector"),
("CastEng", "engActor"),
("CastChi", "chiActor"),
("OriginalLang", "originalLanguage"),
("Bilingual", "bilingual"), 
("AudioLang", "audioLanguage"),
("SubtitleLang", "subtitleLanguage"), 
("RegionCode", "regionCode"),
("FirstReleaseYear", "firstReleaseYear"),
("IsEpisodic", "episodic"), 
("IsVOD", "isVod"),
("ImageWithTitle", "withImageTitle"),
("PortraitImage", "oriPortraitImage"),
("RecordableForCatchUp", "catchUpRecordable"),
("CPInternalUniqueID", "cpInternalId"),
("CPInternalSeriesID", "cpInternalSeriesId"),
("Recordable", "recordable"),
("IsNPVRProg", "isNpvrProg"),
("IsRestartTV", "isRestartTv"),
("EffectiveDate", "effectiveDay"),
("ExpirationDate", "expirationDay"),
("MediaID", "mediaId"),
("CID", "cid"), 
("SID", "sid"), 
("CreatedBy", "createdBy"),
("Premier", "premier"),
("HKTAMChannelID", "hktamChannelId"),
("HKTAMProgramID", "hktamProgramId"),
("HKTAMEpisodeID", "hktamEpisodeId")
])

injestHeader=[
"progId",
"channelId",
"txDate",
"actualTime",
"engName",
"chiName",
"engSponsor",
"chiSponsor",
"engSeries",
"chiSeries",
"engVersion",
"chiVersion",
"seasonNum",
"engSeasonName",
"chiSeasonName",
"episodeNum",
"engEpisodeName",
"chiEpisodeName",
"engSynopsis",
"chiSynopsis",
"engShortSynopsis",
"chiShortSynopsis",
"isLive",
"classification",
"genre",
"subGenre",
"engDirector",
"chiDirector",
"engActor",
"chiActor",
"originalLanguage",
"bilingual",
"audioLanguage",
"subtitleLanguage",
"regionCode",
"firstReleaseYear",
"episodic",
"isVod",
"withImageTitle",
"oriPortraitImage",
"catchUpRecordable",
"cpInternalId",
"cpInternalSeriesId",
"recordable",
"isNpvrProg",
"isRestartTv",
"effectiveDay",
"expirationDay",
"mediaId",
"hktamChannelId",
"hktamProgramId",
"hktamEpisodeId",
"createdBy",
"modifiedBy"
]